# Generated by Django 3.0.8 on 2020-12-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('destacada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Importar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('subcodigo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('guard', models.CharField(blank=True, max_length=50, null=True)),
                ('telas', models.CharField(blank=True, max_length=50, null=True)),
                ('diseño', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('secundaria', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('talle', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_de_barras', models.CharField(max_length=100)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('cadera', models.CharField(blank=True, max_length=50, null=True)),
                ('manga', models.CharField(blank=True, max_length=50, null=True)),
                ('siza', models.CharField(blank=True, max_length=50, null=True)),
                ('tiro', models.CharField(blank=True, max_length=50, null=True)),
                ('bajo_busto', models.CharField(blank=True, max_length=50, null=True)),
                ('cintura', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Importar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barras', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('subcodigo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('guard', models.CharField(blank=True, max_length=50, null=True)),
                ('telas', models.CharField(blank=True, max_length=50, null=True)),
                ('diseño', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('faltante', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('secundaria', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('oferta', models.BooleanField(default=False)),
                ('lomejor', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('proveedores', models.BooleanField(default=False)),
                ('categorias', models.ManyToManyField(blank=True, related_name='categorias', to='store.Categorias')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Talles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('subcodigo', models.CharField(max_length=50)),
                ('talle', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_de_barras', models.CharField(max_length=100)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('cadera', models.CharField(blank=True, max_length=50, null=True)),
                ('manga', models.CharField(blank=True, max_length=50, null=True)),
                ('siza', models.CharField(blank=True, max_length=50, null=True)),
                ('tiro', models.CharField(blank=True, max_length=50, null=True)),
                ('bajo_busto', models.CharField(blank=True, max_length=50, null=True)),
                ('cintura', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'verbose_name_plural': 'Talles',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(help_text='La imagen debe ser 1.5 mas ancha que alta. Minimo 1000x670px ', upload_to='images/')),
                ('categorias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='store.Categorias')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
