# Generated by Django 3.0.8 on 2021-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
