# Generated by Django 3.0.8 on 2020-12-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lomejor',
            new_name='visible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='codigo_de_barras',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detalle_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diseño',
        ),
        migrations.RemoveField(
            model_name='product',
            name='faltante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secundaria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telas',
        ),
        migrations.AlterField(
            model_name='talles',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
