# Generated by Django 3.0.8 on 2020-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201204_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talles',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='talles',
            name='talle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
