# Generated by Django 3.0.8 on 2020-12-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201204_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talles',
            name='bajo_busto',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='cadera',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='cintura',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='siza',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='tamaño_caja',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='tiro',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='talles',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
