# Generated by Django 3.0.8 on 2020-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201021_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sexo',
            new_name='Descripción',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Modelo',
        ),
        migrations.AddField(
            model_name='product',
            name='Sexo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bajo_busto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cintura',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manga',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='siza',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
