# Generated by Django 3.0.8 on 2020-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201214_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_de_barras',
            field=models.CharField(max_length=100),
        ),
    ]
