# Generated by Django 3.0.8 on 2020-12-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201214_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='talles',
            name='codigo_de_barras',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
