# Generated by Django 3.0.8 on 2021-03-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210315_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='subcatcol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Categorias'),
        ),
        migrations.DeleteModel(
            name='SubCatCol',
        ),
    ]
