# Generated by Django 3.0.8 on 2020-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_talles_codigo_de_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcodigo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
