# Generated by Django 3.0.8 on 2020-12-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_subcodigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcodigo',
        ),
    ]
