# Generated by Django 3.0.8 on 2021-04-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
