# Generated by Django 3.0.8 on 2020-12-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_de_barras',
            field=models.IntegerField(default=0),
        ),
    ]
