# Generated by Django 3.0.8 on 2021-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='importar',
            name='secundaria',
        ),
        migrations.AlterField(
            model_name='importar',
            name='codigo_de_barras',
            field=models.CharField(max_length=50),
        ),
    ]
