# Generated by Django 3.0.8 on 2020-12-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201218_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcodigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talles',
            name='subcodigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
