# Generated by Django 3.0.8 on 2021-04-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210418_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='codigo_de_barras',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcodigo',
        ),
        migrations.RemoveField(
            model_name='talles',
            name='codigo_de_barras',
        ),
    ]
