# Generated by Django 3.0.8 on 2020-12-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201218_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('subcodigo', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('guard', models.CharField(blank=True, max_length=50, null=True)),
                ('telas', models.CharField(blank=True, max_length=50, null=True)),
                ('diseño', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('secundaria', models.ImageField(upload_to='products/')),
                ('talle', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_de_barras', models.CharField(max_length=100)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('cadera', models.CharField(blank=True, max_length=50, null=True)),
                ('manga', models.CharField(blank=True, max_length=50, null=True)),
                ('siza', models.CharField(blank=True, max_length=50, null=True)),
                ('tiro', models.CharField(blank=True, max_length=50, null=True)),
                ('bajo_busto', models.CharField(blank=True, max_length=50, null=True)),
                ('cintura', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='talles',
            name='bajo_busto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='cadera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='cintura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='largo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='manga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='siza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='tamaño_caja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='tiro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talles',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
