# Generated by Django 3.0.8 on 2020-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201221_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importar',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='importar',
            name='subcodigo',
            field=models.CharField(max_length=50),
        ),
    ]
