# Generated by Django 3.0.8 on 2020-12-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201221_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
