# Generated by Django 3.0.8 on 2021-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210428_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='importar',
            name='cantidad_cajas',
            field=models.IntegerField(default=0),
        ),
    ]
