# Generated by Django 3.0.8 on 2021-05-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_importar_cantidad_cajas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importar',
            name='bajo_busto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='cadera',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='cintura',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='largo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='manga',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='siza',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='talle',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importar',
            name='tiro',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
