# Generated by Django 3.0.8 on 2020-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importar',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
