# Generated by Django 3.0.8 on 2020-12-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_importar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='talles',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
