# Generated by Django 3.0.8 on 2020-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_talles_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_de_barras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcodigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talles',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talles',
            name='subcodigo',
            field=models.CharField(max_length=50),
        ),
    ]
