# Generated by Django 3.0.8 on 2021-05-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210529_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importar',
            name='talle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
