# Generated by Django 3.0.8 on 2021-05-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210529_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importar',
            name='bajo_busto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='cadera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='cintura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='largo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='manga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='siza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importar',
            name='tiro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
