# Generated by Django 3.0.8 on 2020-12-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201222_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='importar',
            options={'verbose_name_plural': 'Importar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='secciones',
            options={'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='talles',
            options={'verbose_name_plural': 'Talles'},
        ),
    ]
