# Generated by Django 3.0.8 on 2021-07-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_importar_codigo_de_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='talles',
            name='cantidad2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
