# Generated by Django 3.0.8 on 2021-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210530_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
