# Generated by Django 3.0.8 on 2021-05-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_delivery_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModelWithChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=255)),
            ],
        ),
    ]
