# Generated by Django 3.0.8 on 2021-05-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_somemodelwithchoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModelWithChoices',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=255),
        ),
    ]
