# Generated by Django 3.0.8 on 2021-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210530_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Armado', 'Armado'), ('Enviado', 'Enviado'), ('Recibido', 'Recibido'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=255),
        ),
    ]
