# Generated by Django 3.0.8 on 2021-05-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210530_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='tamaño_caja',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='ubicacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
