# Generated by Django 3.0.8 on 2021-05-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210530_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='tamaño_caja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
