# Generated by Django 3.0.8 on 2021-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210530_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
