# Generated by Django 3.0.8 on 2020-10-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='portada',
            new_name='image',
        ),
    ]
