# Generated by Django 3.0.8 on 2020-11-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201119_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='store.Categorias'),
            preserve_default=False,
        ),
    ]
