# Generated by Django 3.0.8 on 2020-11-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201120_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bajo_busto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cadera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cintura',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='siza',
        ),
        migrations.RemoveField(
            model_name='product',
            name='talle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tiro',
        ),
        migrations.AddField(
            model_name='categorias',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
    ]
