# Generated by Django 3.0.8 on 2020-11-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201120_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='store.Categorias'),
        ),
        migrations.CreateModel(
            name='Talles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
