# Generated by Django 3.0.8 on 2020-11-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201120_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='talle',
        ),
    ]
