# Generated by Django 3.0.8 on 2020-11-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201120_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secundaria',
        ),
    ]
