# Generated by Django 3.0.8 on 2020-11-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201120_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='talle',
        ),
        migrations.AddField(
            model_name='talles',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
    ]
